name: Java CI with Maven and Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21' # puedes ajustar la versión según necesites

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test