name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install OpenJDK 22 early access
        run: |
          sudo apt-get install -y openjdk-22-ea-21-jdk
          echo "JAVA_HOME=$(which java)" >> $GITHUB_ENV
          echo "::add-path::$(which java)"

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test